astro/urls.py
from django.urls import path
from .views import index, register, dashboard, profile_list, profile_image_upload, dweet_image_upload, comment_image_upload, reply_image_upload, profile, dweet, comment, reply, dweet_edit, comment_edit, reply_edit

app_name = 'astro'

urlpatterns = [
    path('', index, name='index'),
    path('register/', register, name='register'),
    path('dashboard/', dashboard, name='dashboard'),
    path('profile_list/', profile_list, name='profile_list'),
    path('profile_image_upload/', profile_image_upload, name='profile_image_upload'),
    path('dweet_image_upload/<int:pk>', dweet_image_upload, name='dweet_image_upload'),
    path('comment_image_upload/<int:pk>', comment_image_upload, name='comment_image_upload'),
    path('reply_image_upload/<int:pk>', reply_image_upload, name='reply_image_upload'),
    path('profile/<int:pk>', profile, name='profile'),
    path('dweet/<int:pk>', dweet, name='dweet'),
    path('comment/<int:pk>', comment, name='comment'),
    path('reply/<int:pk>', reply, name='reply'),
    path('dweet_edit/<int:pk>', dweet_edit, name='dweet_edit'),
    path('comment_edit/<int:pk>', comment_edit, name='comment_edit'),
    path('reply_edit/<int:pk>', reply_edit, name='reply_edit'),
]

astroproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('astro.urls')),
    path('admin/', admin.site.urls),
]

#Add URL maps to redirect the base URL to our application
urlpatterns += [
    path('', RedirectView.as_view(url='/astro/', permanent=True)),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

astro/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Dweet, Comment, Reply, ProfileImage, DweetImage, CommentImage, ReplyImage

class ProfileImageForm(forms.ModelForm):
    '''Form for the ProfileImage Model'''
    class Meta:
        model = ProfileImage
        fields = ('image',)
        
class DweetImageForm(forms.ModelForm):
    '''Form for the DweetImage Model'''
    class Meta:
        model = DweetImage
        fields = ('image',)
        
class CommentImageForm(forms.ModelForm):
    '''Form for the CommentImage Model'''
    class Meta:
        model = CommentImage
        fields = ('image',)
        
class ReplyImageForm(forms.ModelForm):
    '''Form for the ReplyImage Model'''
    class Meta:
        model = ReplyImage
        fields = ('image',)

class DweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Dweet something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )

    class Meta:
        model = Dweet
        exclude = ("user", "comments", "reactions", "dweetImage")
        
class CommentForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Comment something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )
    
    class Meta:
        model = Comment
        exclude = ("user", "replies", "reactions", "commentImage")
        
class ReplyForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Reply something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label = "",
    )
    
    class Meta:
        model = Reply
        exclude = ("user", "reactions", "replyImage")
        
class DweetEditForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "class": "textarea is-success is-medium",
            }
        ),
        label = "",
    )
    
    class Meta:
        model = Dweet
        exclude = ("user", "comments", "reactions", "dweetImage")
        
class CommentEditForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "class": "textarea is-success is-medium",
            }
        ),
        label = "",
    )
    
    class Meta:
        model = Comment
        exclude = ("user", "replies", "reactions", "commentImage")
        
class ReplyEditForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "class": "textarea is-success is-medium",
            }
        ),
        label = "",
    )
    
    class Meta:
        model = Reply
        exclude = ("user", "reactions", "replyImage")
        
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('email', 'first_name', 'last_name',)

astro/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import DweetForm, CommentForm, ReplyForm, ProfileImageForm, DweetImageForm, CommentImageForm, ReplyImageForm, CustomUserCreationForm, DweetEditForm, CommentEditForm, ReplyEditForm
from .models import Dweet, Comment, Reply, Profile, ProfileImage, DweetImage, CommentImage, ReplyImage

# Create your views here.

def index(request):
    return render(request, "astro/index.html")

def dashboard(request):
    form = DweetForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.user = request.user
            dweet.save()
            return redirect("astro:dweet", dweet.id)
        
    followed_dweets = Dweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")

    return render(
        request,
        "astro/dashboard.html",
        {"form": form, "dweets": followed_dweets},
    )
    
def profile_image_upload(request):
    '''Process profile images uploaded by users'''
    if request.method == 'POST':
        form = ProfileImageForm(
            request.POST,
            request.FILES
        )
        if form.is_valid():
            profileImage = form.save(commit=False)
            profileImage.user = request.user
            profileImage.save()
            img_obj = form.instance
            current_user_profile = request.user.profile
            current_user_profile.profileImage = img_obj.image
            current_user_profile.save()
            return render(
                request,
                "astro/profile_image_upload.html",
                {"form": form, "img_obj": img_obj}
            )
    else:
        form = ProfileImageForm()
        return render(
            request,
            "astro/profile_image_upload.html",
            {"form": form}
        )
        
def dweet_image_upload(request, pk):
    '''Process dweet images uploaded by users'''
    dweet = Dweet.objects.get(pk=pk)
    if request.method == "POST":
        form = DweetImageForm(
            request.POST,
            request.FILES
        )
        if form.is_valid():
            dweetImage = form.save(commit=False)
            dweetImage.user = request.user
            dweetImage.save()
            img_obj = form.instance
            dweet.dweetImage = img_obj.image
            dweet.save()
            return render(
                request,
                "astro/dweet_image_upload.html",
                {"form": form, "img_obj": img_obj, "dweet": dweet}
            )
    else:
        form = DweetImageForm()
        return render(
            request,
            "astro/dweet_image_upload.html",
            {"form": form, "dweet": dweet}
        )
        
def comment_image_upload(request, pk):
    '''Process comment images uploaded by users'''
    comment = Comment.objects.get(pk=pk)
    if request.method == "POST":
        form = CommentImageForm(
            request.POST,
            request.FILES
        )
        if form.is_valid():
            commentImage = form.save(commit=False)
            commentImage.user = request.user
            commentImage.save()
            img_obj = form.instance
            comment.commentImage = img_obj.image
            comment.save()
            return render(
                request,
                "astro/comment_image_upload.html",
                {"form": form, "img_obj": img_obj, "comment": comment}
            )
    else:
        form = CommentImageForm()
        return render(
            request,
            "astro/comment_image_upload.html",
            {"form": form, "comment": comment}
        )
        
def reply_image_upload(request, pk):
    '''Process reply images uploaded by users'''
    reply = Reply.objects.get(pk=pk)
    if request.method == "POST":
        form = ReplyImageForm(
            request.POST,
            request.FILES
        )
        if form.is_valid():
            replyImage = form.save(commit=False)
            replyImage.user = request.user
            replyImage.save()
            img_obj = form.instance
            reply.replyImage = img_obj.image
            reply.save()
            return render(
                request,
                "astro/reply_image_upload.html",
                {"form": form, "img_obj": img_obj, "reply": reply}
            )
    else:
        form = ReplyImageForm()
        return render(
            request,
            "astro/reply_image_upload.html",
            {"form": form, "reply": reply}
        )
                
def dweet(request, pk):
    dweet = Dweet.objects.get(pk=pk)
    form = CommentForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
            dweet.comments.add(comment.id)
            dweet.save()
            return redirect("astro:comment", comment.id)
    
    return render(
        request,
        "astro/dweet.html",
        {"form": form, "dweet": dweet}
    )
    
def dweet_edit(request, pk):
    '''Edit Dweets for Users'''
    context = {}
    dweet = Dweet.objects.get(pk=pk)
    initial_dweet = {
        "body": dweet.body
    }
    form = DweetEditForm(request.POST or None, initial=initial_dweet)
    context['form'] = form
    context['dweet'] = dweet
    if request.method == "POST":
        if form.is_valid():
            updated_dweet = form.save(commit=False)
            dweet.body = updated_dweet.body
            dweet.save()
            return redirect("astro:dweet", dweet.id)
    return render(
        request,
        "astro/dweet_edit.html",
        context
    )
    
def comment(request, pk):
    comment = Comment.objects.get(pk=pk)
    dweet = Dweet.objects.get(comments__id=comment.id)
    form = ReplyForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.save()
            comment.replies.add(reply.id)
            comment.save()
            return redirect("astro:comment", comment.id)
            
    return render(
        request,
        "astro/comment.html",
        {"form": form, "comment": comment, "dweet": dweet}
    )
    
def comment_edit(request, pk):
    '''Edit Comments for Users'''
    context = {}
    comment = Comment.objects.get(pk=pk)
    initial_comment = {
        'body': comment.body
    }
    form = CommentEditForm(request.POST or None, initial=initial_comment)
    context['form'] = form
    context['comment'] = comment
    if request.method == "POST":
        if form.is_valid():
            updated_comment = form.save(commit=False)
            comment.body = updated_comment.body
            comment.save()
            return redirect("astro:comment", comment.id)
    return render(
        request,
        "astro/comment_edit.html",
        context
    )
    
def reply(request, pk):
    reply = Reply.objects.get(pk=pk)
    comment = Comment.objects.get(replies__id=reply.id)
    return render(
        request,
        "astro/reply.html",
        {"reply": reply, "comment": comment}
    )
    
def reply_edit(request, pk):
    '''Edit Replies for Users'''
    context = {}
    reply = Reply.objects.get(pk=pk)
    initial_reply = {
        'body': reply.body
    }
    form = ReplyEditForm(request.POST or None, initial=initial_reply)
    context['form'] = form
    context['reply'] = reply
    if request.method == "POST":
        if form.is_valid():
            updated_reply = form.save(commit=False)
            reply.body = updated_reply.body
            reply.save()
            return redirect("astro:reply", reply.id)
    return render(
        request,
        "astro/reply_edit.html",
        context
    )

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "astro/profile_list.html", {"profiles": profiles})

def profile(request, pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, "astro/profile.html", {"profile": profile})

def register(request):
    if request.method == "GET":
        return render(
            request, "astro/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse('astro:dashboard'))

astro/templates/astro/comment.html
{% extends "base.html" %}

{% block content %}
    <div class="column">
        <div class="box">
            <a href="{% url 'astro:dweet' dweet.id %}">
                <button class="button is-dark is-outlined is-fullwidth">
                    Back To Dweet
                </button>
            </a>
        </div>
    </div>
    <div class="column">
        <a href="{% url 'astro:profile' comment.user.profile.id %}">
            <div class="block">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-left">
                                <figure class="image is-48x48">
                                    <img src="{{ comment.user.profile.profileImage.url }}" alt="profile picture">
                                </figure>
                            </div>
                            <div class="media-content">
                                <p class="title is-4">
                                    {{ comment.user.username }}
                                </p>
                                <p class="subtitle is-6">
                                    @{{ comment.user.username|lower }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% if comment.commentImage %}
            <div class="box">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-center">
                                <figure class="image is-fullwidth">
                                    <img src="{{ comment.commentImage.url }}" alt="comment picture">
                                </figure>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="block">
            <span class="is-small has-text-grey-light">
                ({{ comment.created_at }})
            </span>
            {{ comment.body }}
        </div>
        {% if comment.user.id == request.user.id %}
            <div class="block">
                <a href="{% url 'astro:comment_image_upload' comment.id %}">
                    <button class="button is-success is-light is-outlined is-fullwidth">
                        Upload Photo
                    </button>
                </a>
            </div>
            <div class="block">
                <a href="{% url 'astro:comment_edit' comment.id %}">
                    <button class="button is-danger is-dark is-outlined is-fullwidth">
                        Edit Comment
                    </button>
                </a>
            </div>
            <div class="column">
                <h1 class="title is-4">
                    Replies: {{ comment.replies.count }}
                </h1>
            </div>
        {% else %}
            <div class="column">
                <h1 class="title is-4">
                    Replies: {{ comment.replies.count }}
                </h1>
            </div>
            <div class="block">
                <div class="block">
                    <h2 class="title is-2">
                        Add a Reply
                    </h2>
                </div>
                <div class="block">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="button is-success is-fullwidth is-medium mt-5" type="submit">
                            Reply
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
        {% for reply in comment.replies.all %}
            <div style="height:5vh">
                <p style="background-color:lightgrey">
                    <br>
                </p>
            </div>
            <a href="{% url 'astro:profile' reply.user.profile.id %}">
                <div class="box">
                    <div class="card">
                        <div class="card-content">
                            <div class="media">
                                <div class="media-left">
                                    <figure class="image is-48x48">
                                        <img src="{{ reply.user.profile.profileImage.url }}" alt="profile picture">
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <p class="title is-4">
                                        {{ reply.user.username }}
                                    </p>
                                    <p class="subtitle is-6">
                                        @{{ reply.user.username|lower }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="{% url 'astro:reply' reply.id %}">
                {% if reply.replyImage %}
                    <div class="box">
                        <div class="card">
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-center">
                                        <figure class="image is-fullwidth">
                                            <img src="{{ reply.replyImage.url }}" alt="reply picture">
                                        </figure>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="box">
                    <span class="is-small has-text-grey-light">
                        ({{ reply.created_at }})
                    </span>
                    {{ reply.body }}
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock content %}

astro/templates/astro/dweet.html
{% extends "base.html" %}

{% block content %}
    <div class="column">
        <a href="{% url 'astro:profile' dweet.user.profile.id %}">
            <div class="block">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-left">
                                <figure class="image is-48x48">
                                    <img  src="{{ dweet.user.profile.profileImage.url }}" alt="profile picture">
                                </figure>
                            </div>
                            <div class="media-content">
                                <p class="title is-4">
                                    {{ dweet.user.username }}
                                </p>
                                <p class="subtitle is-6">
                                    @{{ dweet.user.username|lower }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {% if dweet.dweetImage %}
            <div class="box">
                <div class="card">
                    <div class="card-content">
                        <div class="media">
                            <div class="media-center">
                                <figure class="image is-fullwidth">
                                    <img src="{{ dweet.dweetImage.url }}" alt="dweet picture">
                                </figure>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="block">
            <span class="is-small has-text-grey-light">
                ({{ dweet.created_at }})
            </span>
            {{ dweet.body }}
        </div>
        {% if dweet.user.id == request.user.id %}
            <div class="block">
                <a href="{% url 'astro:dweet_image_upload' dweet.id %}">
                    <button class="button is-success is-light is-outlined is-fullwidth">
                        Upload Photo
                    </button>
                </a>
            </div>
            <div class="block">
                <a href="{% url 'astro:dweet_edit' dweet.id %}">
                    <button class="button is-danger is-dark is-outlined is-fullwidth">
                        Edit Dweet
                    </button>
                </a>
            </div>
        {% endif %}
        <div class="column">
            <h1 class="title is-4">
                Comments: {{ dweet.comments.count }}
            </h1>
            <div class="block">
                <div class="block">
                    <h2 class="title is-2">
                        Add a Comment
                    </h2>
                </div>
                <div class="block">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="button is-success is-fullwidth is-medium mt-5" type="submit">
                            Comment
                        </button>
                    </form>
                </div>
            </div>
            {% for comment in dweet.comments.all %}
                <div style="height:5vh">
                    <p style="background-color:lightgrey">
                        <br>
                    </p>
                </div>
                <a href="{% url 'astro:profile' comment.user.profile.id %}">
                    <div class="box">
                        <div class="card">
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-left">
                                        <figure class="image is-48x48">
                                            <img  src="{{ comment.user.profile.profileImage.url }}" alt="profile picture">
                                        </figure>
                                    </div>
                                    <div class="media-content">
                                        <p class="title is-4">
                                            {{ comment.user.username }}
                                        </p>
                                        <p class="subtitle is-6">
                                            @{{ comment.user.username|lower }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                <a href="{% url 'astro:comment' comment.id %}">
                    {% if comment.commentImage %}
                        <div class="box">
                            <div class="card">
                                <div class="card-content">
                                    <div class="media">
                                        <div class="media-center">
                                            <figure class="image is-fullwidth">
                                                <img src="{{ comment.commentImage.url }}" alt="comment picture">
                                            </figure>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <div class="box">
                        <span class="is-small has-text-grey-light">
                            ({{ comment.created_at }})
                        </span>
                        {{ comment.body }}
                    </div>
                    <div class="box">
                        Replies: {{ comment.replies.count }}
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

astro/templates/astro/profile.html
<!-- dwitter/templates/dwitter/profile.html -->

{% extends 'base.html' %}

{% block content %}

<div class="column">
    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s Dweets
    </h1>
    <div class="box">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-center">
                        <figure class="image is-100x100">
                            <img src="{{ profile.profileImage.url }}" alt="profile picture">
                        </figure>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if profile.user.id == request.user.id %}
        <ul>
            <li>
                <a href="{% url 'astro:profile_image_upload' %}">
                    • Change Profile Picture
                </a>
            </li>
            <li>
                <a href="{% url 'password_change' %}">
                    • Change Password
                </a>
            </li>
        </ul>
    {% endif %}
    </div>
    <form method="post">
    {% csrf_token %}
    <div class="buttons has-addons">
    {% if profile in user.profile.follows.all %}
        <button class="button is-success is-static">Follow</button>
        <button class="button is-danger" name="follow" value="unfollow">
            Unfollow
        </button>
    {% else %}
        <button class="button is-success" name="follow" value="follow">
            Follow
        </button>
        <button class="button is-danger is-static">Unfollow</button>
    {% endif %}
    </div>
    </form>
    <div class="content">
        {% for dweet in profile.user.dweets.all %}
            <div style="height:5vh">
                <p style="background-color:lightgrey">
                    <br>
                </p>
            </div>
            <a href="{% url 'astro:dweet' dweet.id %}">
                <div class="box">
                    {% if dweet.dweetImage %}
                        <div class="card">
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-center">
                                        <figure class="image is-100x100">
                                            <img src="{{ dweet.dweetImage.url }}" alt="dweet image">
                                        </figure>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <span class="is-small has-text-grey-light">
                        ({{ dweet.created_at }})
                    </span>
                    {{ dweet.body }}
                    <h4>
                        Comments: {{ dweet.comments.count }}
                    </h4>
                </div>
            </a>
        {% endfor %}
    </div>
</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'astro:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'astro:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'astro:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

astro/templates/astro/register.html
{% extends 'base_registration.html' %}

{% block content %}

    <h1>Astro</h1>
    <h2>Registration:</h2>

    <form method="post">
        {% csrf_token %}
        {{form}}
        <br>
        <input type="submit" value="Register">
    </form>
    <br>

    <a href="{% url 'login' %}">Back to login</a>

{% endblock %}